#VAULT ----------------------------------------------------------------------------------------------
version: '1.0'
services:
  vault-app:
    container_name: vault-app
    build:
      context: .
    ports:
      - "8095:8095"
    depends_on:
      - vault

  vault:
    image: vault:1.6.1
    container_name: vault
    command: ["sh", "-c", "vault server -config /vault/config/config.hcl"]
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - ./vault/config/config.hcl:/vault/config/config.hcl

  vault-init:
    image: vault:1.6.1
    container_name: vault-init
    depends_on:
      - vault
    volumes:
      - ./vault/scripts/init-vault.sh:/vault/scripts/init-vault.sh
      - ./vault/keys:/vault/keys
    environment:
      VAULT_ADDR: $${vault.addr}

      VAULT_DEV_ROOT_TOKEN_ID: root
    command: [ "sh", "-c", "/vault/scripts/init-vault.sh" ]