#VAULT ----------------------------------------------------------------------------------------------
version: '3.8'
services:
  vault-app:
    container_name: vault-app
    build:
      context: .
    ports:
      - "8095:8095"
    depends_on:
      - vault

  vault:
    image: hashicorp/vault:1.11.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=root

  vault-init:
      image: hashicorp/vault:1.11.0
      depends_on:
        - vault
      environment:
        VAULT_ADDR: http://127.0.0.1:8200
      entrypoint: >
        /bin/sh -c "
        export VAULT_ADDR='http://127.0.0.1:8200';
        sleep 5;  
        vault operator unseal zSmXi4aY8hWvWn6Ljkg6eJgS/DQVHd0kfemk95SyH/Y=;
        vault login root;
        vault secrets enable -path=secret kv-v2;
        vault kv put secret/myconfig username=admin password=secret123;
        "


volumes:
  vault_data: {
  }
