server.port=8095

# Vault
vault.port=8200
vault.version=v1
vault.host=0.0.0.0
vault.addr=http://${vault.host}:${vault.port}
vault.addr.with.version=${vault.addr}/${vault.version}
vault.unseal=${vault.addr.with.version}/sys/unseal

# changed path for both on relative link
vault.key-1.path=/home/yevh/Desktop/DemoProject/MentalBot/Vault/src/main/resources/vault/keys/key-1
vault.key-2.path=/home/yevh/Desktop/DemoProject/MentalBot/Vault/src/main/resources/vault/keys/key-2

vault.root-token=${VAULT_ROOT_TOKEN}