server.port=8095

# Vault
vault.host=0.0.0.0
vault.port=8200
vault.addr=http://${vault.host}:${vault.port}
vault.unseal=${vault.addr}/v1/sys/unseal
vault.version=/v1

# changed path for both on relative link
vault.key-1.path=/home/yevh/Desktop/DemoProject/MentalBot/Vault/src/main/resources/vault/keys/key-1
vault.key-2.path=/home/yevh/Desktop/DemoProject/MentalBot/Vault/src/main/resources/vault/keys/key-2

vault.root-token=${VAULT_ROOT_TOKEN}